# patch metricsPort
- op: replace
  path: '/spec/ports/0/port'
  value: '{{ .Values.metricsPort }}'
- op: replace
  path: '/spec/ports/0/targetPort'
  value: '{{ .Values.metricsPort }}'
# remove upstream matchLabels
- op: remove
  path: '/spec/selector/app'
- op: remove
  path: /metadata/labels/name