version: 2.1
orbs:
  architect: giantswarm/architect@5.11.2

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package and push caicloud-event-exporter-app chart
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: caicloud-event-exporter-app
        persist_chart_archive: true
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
        push_to_oci_registry: true
