resources:
  - https://raw.githubusercontent.com/caicloud/event_exporter/v1.0.0/deploy/deploy.yml
  - additional-resources/network-policy.yaml
namespace: "{{ .Release.Namespace }}"
images:
  - name: "caicloud/event-exporter"
    newName: "{{ .Values.image.repository }}"
    newTag: "{{ .Values.image.tag }}"
transformers:
  - ./labels-transformer.yaml
  - ./matchlabels-transformer.yaml
# TODO(kuba):
# - NetworkPolicy to allow scraping
# - customizable port in values.yaml
# - pod security context
# - pod resource limits + vpa
# - resource name overrides - everything's called "event-exporter", which is bad
# - PodSecurityPolicy
# - Prometheus labels on the service AND PodMonitor
