---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels-transformer-metadata-all
labels:
  gst: '{{- include "labels.common" . | indent 4 }}'
# fieldSpecs from https://github.com/kubernetes-sigs/kustomize/blob/a3bf3ba/api/konfig/builtinpluginconsts/commonlabels.go
# but omits any `matchLabels`. These are handeled by matchlabels-transformer.yaml
# update if neccessary!
fieldSpecs:
- path: metadata/labels
  create: true
---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels-transformer-template-labels
labels:
  gst: '{{- include "labels.common" . | indent 8 }}'
fieldSpecs:
- path: spec/template/metadata/labels
  create: true
  version: v1
  kind: Deployment
