apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
    name: event-exporter
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
    name: event-exporter
  name: caicloud-event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
    name: event-exporter
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
  selector:
    app: event-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
    name: event-exporter
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: event-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.metricsPort }}
        prometheus.io/scrape: "true"
      labels:
        app: event-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        giantswarm.io/service_type: managed
        helm.sh/chart: {{ include "chart" . }}
    spec:
      containers:
      - args:
        - --eventType=Warning
        - --eventType=Normal
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: Always
        name: event-exporter
        ports:
        - containerPort: {{ .Values.metricsPort }}
          name: http
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 100
      serviceAccountName: caicloud-event-exporter
      terminationGracePeriodSeconds: 30
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    giantswarm.io/service_type: managed
    helm.sh/chart: {{ include "chart" . }}
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: {{ .Values.metricsPort }}
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
  policyTypes:
  - Egress
  - Ingress
