apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.common" . | indent 4 }}
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels.common" . | indent 4 }}
  name: caicloud-event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" . | indent 4 }}
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels.common" . | indent 4 }}
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.metricsPort | quote }}
        prometheus.io/scrape: "true"
      labels:
        {{- include "labels.common" . | indent 8 }}
    spec:
      containers:
      - args:
        - --port={{ .Values.metricsPort }}
        - --eventType=Warning
        - --eventType=Normal
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: IfNotPresent
        name: event-exporter
        ports:
        - containerPort: {{ .Values.metricsPort }}
          name: http
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 100
      serviceAccountName: caicloud-event-exporter
      terminationGracePeriodSeconds: 30
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "labels.common" . | indent 4 }}
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - targetPort: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "labels.common" . | indent 4 }}
  name: caicloud-event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: {{ .Values.metricsPort }}
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" . }}
  policyTypes:
  - Egress
  - Ingress
