apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: '{{ include "name" . }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: '{{ .metricsPort }}'
          protocol: TCP
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
    - Ingress
