apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: event-exporter
spec:
  namespaceSelector:
    matchNames:
      - '{{ .Release.Namespace }}'
  selector:
    # filled by matchlabels-transformer.yaml
    matchLabels: {}
  podMetricsEndpoints:
    - port: http
